apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
spec:
  rules:
    - host: dashboard.com
      http:
        paths:
          - backend:
              serviceName: kubernetes-dashboard
              servicePort: 80