apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookapi
  template:
    metadata:
      labels:
        app: bookapi
    spec:
      containers:
        - name: bookapi
          image: shohagrana64/bookapi:latest
          ports:
            - containerPort: 80
