apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookapi-deployment
spec:
  replicas: 2
  selector:
    matchLabels:  # matchLabels supports replicaSets,Deployments, Jobs, DaemonSet # No matchLabels on older resources such as ReplicationControllers and Services.
      app: bookapi
#      role:
#      tier:
  template:
    metadata:
      labels:
        app: bookapi
#        role:
#        tier:
#      annotation:  #this is used when new version of app is going to be published
#        kubernetes.io/change-cause: "Update to green kuard"
#  minReadySeconds: 60 # this is the minimum amount of time to wait after seeing a pod become healthy before moving on to the next pod. this is inside spec:
#  progressDeadlineSeconds: 600 # This sets the progress deadline to 10 minutes. If any particular stage in the rollout fails to progress in 10 minutes, then the deployment is marked as failed, and all attempts to move the deployment forward are halted.

    spec:
      containers:
        - name: bookapi
          image: shohagrana64/bookapi:latest
#          resources:
#            requests:
#              cpu: 100m
#              memory: 100Mi

          ports:
            - containerPort: 80
