apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: centos:7
        command:
          - "bin/bash"
          - "-c"
          - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: never #OnFailure is better to use since it doesn't create a lot of junk in the cluster.

      #kubectl create -f job-example.yaml
      #kubectl get jobs
      #kubectl get pods
      #kubectl logs podName

      #kubectl describe jobs countdown
      #kubectl delete jobs countdown