apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: example-rs
  #labels:
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
    matchExpressions:
      - {key: tier, operator: In, values:[frontend]}
    #template is exactly the same as the pod manifest file (except api version and kind)
  template:
    metadata:
      name: example-pod
      labels:
        app: example-app
        tier: frontend
    spec:
      containers:
        - name: example-container
          image: example
          ports:
            - containerPort: 80