apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: bookapi-rs
  #labels:
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookapi
#    matchExpressions:
#      - {key: tier, operator: In, values:[frontend]}
    #template is exactly the same as the pod manifest file (except api version and kind)
  template:
    metadata:
      name: bookapi-pod
      labels:
        app: bookapi
#        tier: frontend
    spec:
      containers:
        - name: bookapi
          image: shohagrana64/bookapi:latest
          ports:
            - containerPort: 80
