apiVersion: v1
kind: Service
metadata:
  name: bookapi-svc
  labels:
    app: bookapi
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "10000"
#    tier:
spec:
  type: NodePort #ClusterIp / LoadBalancer
  ports:
    - port: 10000
      nodePort: 30080
#      targetPort:
#      protocol: TCP
  selector:
    app: bookapi
#    tier: