apiVersion: v1
kind: Service
metadata:
  name: bookapi-svc
  labels:
    app: bookapi
#    tier:
spec:
  type: NodePort #ClusterIp / LoadBalancer
  ports:
    - port: 10000
      nodePort: 30080
  selector:
    app: bookapi
#    tier: